<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="smart_car">
  <!-- Define properties -->
  <xacro:property name="wheel_diameter" value="0.064"/>
  <xacro:property name="wheel_width" value="0.025"/>
  <xacro:property name="wheelbase_length" value="0.257"/>
  <xacro:property name="wheelbase_width" value="0.17"/>
  <xacro:property name="base_length" value="0.2"/>
  <xacro:property name="base_width" value="0.1"/>

  <!-- Base link -->
  <link name="base_link">

  </link>
  
  <!-- Chassis link -->
  <link name="chassis_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} 0.01"/>
      </geometry>
      <material name="grey">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} 0.01"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="1e-3" ixy="0.0" ixz="0.0" iyy="1e-3" iyz="0.0" izz="1e-3"/>
    </inertial>
  </link>

  <!-- Base footprint -->
  <link name="base_footprint">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} 0.01"/>
      </geometry>
      <material name="transparent">
        <color rgba="0 0 0 0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} 0.01"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="1e-4" ixy="0.0" ixz="0.0" iyy="1e-4" iyz="0.0" izz="1e-4"/>
    </inertial>
  </link>

  <!-- Joint to connect base_footprint to base_link -->
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>
 
  <joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis_link"/>
    <origin xyz="0.05 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

 <!-- Wheels -->
<link name="back_left_wheel">
  <visual>
    <origin rpy="0 1.57075 1.57075" xyz="0 0 0"/>
    <geometry>
      <cylinder radius="${wheel_diameter / 2}" length="${wheel_width}"/>
    </geometry>
    <material name="black">
      <color rgba="0 0 0 1"/>
    </material>
  </visual>
  <collision>
    <origin rpy="0 1.57075 1.57075" xyz="0 0 0"/>
    <geometry>
      <cylinder radius="${wheel_diameter / 2}" length="${wheel_width}"/>
    </geometry>
  </collision>
  <inertial>
    <mass value="0.5"/>
    <origin xyz="0 0 0"/>
    <inertia ixx="1e-4" ixy="0.0" ixz="0.0" iyy="1e-4" iyz="0.0" izz="1e-4"/>
  </inertial>
</link>

<link name="back_right_wheel">
  <visual>
    <origin rpy="0 1.57075 1.57075" xyz="0 0 0"/>
    <geometry>
      <cylinder radius="${wheel_diameter / 2}" length="${wheel_width}"/>
    </geometry>
    <material name="black">
      <color rgba="0 0 0 1"/>
    </material>
  </visual>
  <collision>
    <origin rpy="0 1.57075 1.57075" xyz="0 0 0"/>
    <geometry>
      <cylinder radius="${wheel_diameter / 2}" length="${wheel_width}"/>
    </geometry>
  </collision>
  <inertial>
    <mass value="0.5"/>
    <origin xyz="0 0 0"/>
    <inertia ixx="1e-4" ixy="0.0" ixz="0.0" iyy="1e-4" iyz="0.0" izz="1e-4"/>
  </inertial>
</link>

<link name="front_left_wheel">
  <visual>
    <origin rpy="0 1.57075 1.57075" xyz="0 0 0"/>
    <geometry>
      <cylinder radius="${wheel_diameter / 2}" length="${wheel_width}"/>
    </geometry>
    <material name="black">
      <color rgba="0 0 0 1"/>
    </material>
  </visual>
  <collision>
    <origin rpy="0 1.57075 1.57075" xyz="0 0 0"/>
    <geometry>
      <cylinder radius="${wheel_diameter / 2}" length="${wheel_width}"/>
    </geometry>
  </collision>
  <inertial>
    <mass value="0.5"/>
    <origin xyz="0 0 0"/>
    <inertia ixx="1e-4" ixy="0.0" ixz="0.0" iyy="1e-4" iyz="0.0" izz="1e-4"/>
  </inertial>
</link>

<link name="front_right_wheel">
  <visual>
    <origin rpy="0 1.57075 1.57075" xyz="0 0 0"/>
    <geometry>
      <cylinder radius="${wheel_diameter / 2}" length="${wheel_width}"/>
    </geometry>
    <material name="black">
      <color rgba="0 0 0 1"/>
    </material>
  </visual>
  <collision>
    <origin rpy="0 1.57075 1.57075" xyz="0 0 0"/>
    <geometry>
      <cylinder radius="${wheel_diameter / 2}" length="${wheel_width}"/>
    </geometry>
  </collision>
  <inertial>
    <mass value="0.5"/>
    <origin xyz="0 0 0"/>
    <inertia ixx="1e-4" ixy="0.0" ixz="0.0" iyy="1e-4" iyz="0.0" izz="1e-4"/>
  </inertial>
</link>

<!-- Steering Links -->
<link name="front_left_wheel_steer">
  <inertial>
    <mass value="0.01"/> 
    <origin xyz="0 0 0"/>
    <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/> 
  </inertial>
</link>

<link name="front_right_wheel_steer">
  <inertial>
    <mass value="0.01"/>
    <origin xyz="0 0 0"/>
    <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/> 
  </inertial>
</link>

<!-- Joints -->
<joint name="back_left_wheel_joint" type="continuous">
  <parent link="base_link"/>
  <child link="back_left_wheel"/>
  <origin xyz="0 ${-wheelbase_width / 2} 0"/>
  <axis xyz="0 1 0"/>
</joint>

<joint name="back_right_wheel_joint" type="continuous">
  <parent link="base_link"/>
  <child link="back_right_wheel"/>
  <origin xyz="0 ${wheelbase_width / 2} 0"/>
  <axis xyz="0 1 0"/>
</joint>

<joint name="front_left_wheel_steer_joint" type="revolute">
  <parent link="base_link"/>
  <child link="front_left_wheel_steer"/>
  <origin xyz="${wheelbase_length } ${-wheelbase_width / 2} 0" rpy="0 0 0"/>
  <axis xyz="0 0 1"/>
  <limit lower="-0.5" upper="0.5" effort="10" velocity="1.0"/>
</joint>

<joint name="front_left_wheel_joint" type="continuous">
  <parent link="front_left_wheel_steer"/>
  <child link="front_left_wheel"/>
  <origin xyz="0 0 0"/>
  <axis xyz="0 1 0"/>
</joint>

<joint name="front_right_wheel_steer_joint" type="revolute">
  <parent link="base_link"/>
  <child link="front_right_wheel_steer"/>
  <origin xyz="${wheelbase_length } ${wheelbase_width / 2} 0" rpy="0 0 0"/>
  <axis xyz="0 0 1"/>
  <limit lower="-0.5" upper="0.5" effort="10" velocity="1.0"/>
</joint>

<joint name="front_right_wheel_joint" type="continuous">
  <parent link="front_right_wheel_steer"/>
  <child link="front_right_wheel"/>
  <origin xyz="0 0 0"/>
  <axis xyz="0 1 0"/>
</joint>


  <!-- IMU Sensor -->
  <link name="imu_link">
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.0001" ixy="3.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
    <visual>
      <geometry>
        <box size="0.02 0.02 0.02"/>
      </geometry>
      <material name="yellow">
        <color rgba="1 1 0 1"/>
      </material>
    </visual>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0.01"/>

  </joint>

  <gazebo reference="imu_link">
    <sensor name="br_imu" type="imu">
        <always_on>true</always_on>
        <update_rate>100</update_rate>
        <imu>
          <angular_velocity>
            <x>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>2e-4</stddev>
              </noise>
            </x>
            <y>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>2e-4</stddev>
              </noise>
            </y>
            <z>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>2e-4</stddev>
              </noise>
            </z>
          </angular_velocity>
          <linear_acceleration>
            <x>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>1.7e-2</stddev>
              </noise>
            </x>
            <y>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>1.7e-2</stddev>
              </noise>
            </y>
            <z>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>1.7e-2</stddev>
              </noise>
            </z>
          </linear_acceleration>
        </imu>
        <plugin name="bytes_imu" filename="libgazebo_ros_imu_sensor.so">
            <ros>
                <remapping>~/out:=imu_data</remapping>
            </ros>
            <initial_orientation_as_reference>false</initial_orientation_as_reference>
        </plugin>
    </sensor>
  </gazebo>



  <!-- LIDAR Sensor -->
  <link name="sllidar_base_link">
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.05"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 1 1"/>
      </material>
    </visual>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="sllidar_base_link"/>
    <origin xyz="${wheelbase_length} 0 0.1"/>
    <axis xyz="0 0 1"/>
  </joint>

  <gazebo reference="sllidar_base_link">
    <sensor name="rplidar_a3" type="ray">
        <always_on>true</always_on>
        <visualize>false</visualize>
        <pose>0.0 0 0.0 0 0 0</pose>
        <update_rate>15</update_rate>
        <ray>
          <scan>
            <horizontal>
              <samples>667</samples>
              <resolution>0.54</resolution>
              <min_angle>0.000000</min_angle>
              <max_angle>6.280000</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.120000</min>
            <max>20</max>
            <resolution>0.54</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.01</stddev>
          </noise>
        </ray>
        <plugin name="bytes_laserscan" filename="libgazebo_ros_ray_sensor.so">
          <ros>
              <remapping>~/out:=scan</remapping>
          </ros>
          <output_type>sensor_msgs/LaserScan</output_type>
          <frame_name>sllidar_base_link</frame_name>
        </plugin>
    </sensor>
    <material>Gazebo/Purple</material>
  </gazebo>



  <gazebo>
  <plugin name="car_control_plugin" filename="libcar_gazebo_plugin.so">
  </plugin>
</gazebo>

</robot>
